let family = {
    "a2": {
        name: "Pendyala Akkamamba",
        description: ["Dommeru"],
        spouse: ["a3"], 
        parents: [],
        siblings: ["a1"],
        children: ["b1","b2","b3","b4","b5","b6","b7"],
        adopted: [],
        gavechild: [],
    },

    "a3": {
        name: "Mullapudi Venkat Rayudu",
        description: ["Tanuku"],
        spouse: ["a2"],
        parents: [],
        siblings: [],
        children: ["b1","b2","b3","b4","b5","b6","b7"],
        adopted: [],
        gavechild: [],  
    },

    "a1": {
        name: "Pendyala Krishna Rao",
        description: ["Dommeru"],
        spouse: ["b1"],
        parents: [],
        siblings: ["a2"],
        children: [],
        adopted: [["c1","b2"]],
        gavechild:[],
    },

    "b1": {
        name: "Mullapudi Ananthalakshmi",
        description: ["Dommeru"],
        spouse: ["a1"],
        parents: ["a2","a3"],
        siblings: ["b2","b3","b4","b5","b6","b7"],
        children:[],
        adopted: [["c1","b2"]],
        gavechild: [],
    },
    
    "b2": {
        name: "Mullapudi Narayanamma",
        description: ["Tanuku"],
        spouse: ["b8"],
        parents: ["a2","a3"],
        siblings: ["b1","b3","b4","b5","b6","b7"],
        children: ["c2","c3","c4","c5"],
        adopted: [],
        gavechild: ["c1","b1"],
    },

    "b8": {
        name: "Nidadavole Venkat Ramayya",
        description: ["Tanuku, adopted from Chitturi?"],
        spouse: ["b2"],
        parents: [],
        siblings: [],
        children: ["c2","c3","c4","c5"],
        adopted: [],
        gavechild: ["c1","b1"],
    },

    "b3": {
        name: "Mullapudi Achhayama",
        description: ["Tanuku"],
        spouse: ["b9"],
        parents: ["a2","a3"],
        siblings: ["b1","b2","b4","b5","b6","b7"],
        children: ["c6","c7","c8","c9","c10"],
        adopted: [],
        gavechild: [],
    },

    "b9": {
        name: "Chitturi Inderayya",
        description: ["Tanuku"],
        spouse: ["b3"],
        parents: [],
        siblings: [],
        children: ["c6","c7","c8","c9","c10"],
        adopted: [],
        gavechild: [],
    },

    "b4": {
        name: "Mullapudi Thimmaraja",
        description: ["Tanuku"],
        spouse: ["b10","b11"],
        parents: ["a2","a3"],
        siblings: ["b1","b2","b3","b5","b6","b7"],
        children: ["c11","c12","c13","c14","c15","c16"],
        adopted: [],
        gavechild: [],
    },
    
 "b10": {
        name: "Bolla Venkatramanamma",
        description: ["first wife"],
        spouse: ["b4"],
        parents: [],
        siblings: ["b15"],
        children: ["c11","c12"],
        adopted: [],
        gavechild: [],
    },
    
    "b11": {
        name: "? Kamala",
        description: ["2nd wife"],
        spouse: ["b4"],
        parents: [],
        siblings: [],
        children: ["c13","c14","c15","c16"],
        adopted: [],
        gavechild: [],
    },

    "b5": {
        name: "Mullapudi Bullinarayanamma",
        description: ["Dommeru"],
        spouse: ["b12"],
        parents: ["a2","a3"],
        siblings: ["b1","b2","b3","b4","b6","b7"],
        children: ["c17","c18","c19","c20","c21","c22","c23","c24","c25","c26"],
        adopted: [],
        gavechild: [],
    },

    "b12": {
        name: "Yalamarthi Sattiraju",
        description: ["Dommeru"],
        spouse: ["b5"],
        parents: [],
        siblings: [],
        children: ["c17","c18","c19","c20","c21","c22","c23","c24","c25","c26"],
        adopted: [],
        gavechild: [],
    },

    "b6": {
        name: "Mullapudi Sri Lakshmi",
        description: ["Kolla"],
        spouse: ["b13"],
        parents: ["a2","a3"],
        siblings: ["b1","b2","b3","b4","b5","b7"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "b13": {
        name: "? Chitturi",
        description: ["Kolla"],
        spouse: ["b6"],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "b7": {
        name: "Mullapudi Lakshmi Devi",
        description: ["Kolla"],
        spouse: ["b14"],
        parents: ["a2","a3"],
        siblings: ["b1","b2","b3","b4","b5","b6"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "b14": {
        name: "? Chitturi",
        description: ["Kolla"],
        spouse: ["b7"],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "b15": {
        name: "",
        description: [],
        spouse: [],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "": {
        name: "",
        description: [],
        spouse: [],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "": {
        name: "",
        description: [],
        spouse: [],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "": {
        name: "",
        description: [],
        spouse: [],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "": {
        name: "",
        description: [],
        spouse: [],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "": {
        name: "",
        description: [],
        spouse: [],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "": {
        name: "",
        description: [],
        spouse: [],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "": {
        name: "",
        description: [],
        spouse: [],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "": {
        name: "",
        description: [],
        spouse: [],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "": {
        name: "",
        description: [],
        spouse: [],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "": {
        name: "",
        description: [],
        spouse: [],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "": {
        name: "",
        description: [],
        spouse: [],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "": {
        name: "",
        description: [],
        spouse: [],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "": {
        name: "",
        description: [],
        spouse: [],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "": {
        name: "",
        description: [],
        spouse: [],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "": {
        name: "",
        description: [],
        spouse: [],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "": {
        name: "",
        description: [],
        spouse: [],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "": {
        name: "",
        description: [],
        spouse: [],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "": {
        name: "",
        description: [],
        spouse: [],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "": {
        name: "",
        description: [],
        spouse: [],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "": {
        name: "",
        description: [],
        spouse: [],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "": {
        name: "",
        description: [],
        spouse: [],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "": {
        name: "",
        description: [],
        spouse: [],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "": {
        name: "",
        description: [],
        spouse: [],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "": {
        name: "",
        description: [],
        spouse: [],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },





}

export default family;