let family = {
    "a2": {
        name: "Pendyala Akkamamba",
        description: ["Dommeru"],
        spouse: ["a3"], 
        parents: [],
        siblings: ["a1"],
        children: ["b1","b2","b3","b4","b5","b6","b7"],
        adopted: [],
        gavechild: [],
    },

    "a3": {
        name: "Mullapudi Venkat Rayudu",
        description: ["Tanuku"],
        spouse: ["a2"],
        parents: [],
        siblings: [],
        children: ["b1","b2","b3","b4","b5","b6","b7"],
        adopted: [],
        gavechild: [],  
    },

    "a1": {
        name: "Pendyala Krishna Rao",
        description: ["Dommeru"],
        spouse: ["b1"],
        parents: [],
        siblings: ["a2"],
        children: [],
        adopted: [["c1","b2"]],
        gavechild:[],
    },

    "b1": {
        name: "Mullapudi Ananthalakshmi",
        description: ["Dommeru"],
        spouse: ["a1"],
        parents: ["a2","a3"],
        siblings: ["b2","b3","b4","b5","b6","b7"],
        children:[],
        adopted: [["c1","b2"]],
        gavechild: [],
    },
    
    "b2": {
        name: "Mullapudi Narayanamma",
        description: ["Tanuku"],
        spouse: ["b8"],
        parents: ["a2","a3"],
        siblings: ["b1","b3","b4","b5","b6","b7"],
        children: ["c2","c3","c4","c5"],
        adopted: [],
        gavechild: ["c1","b1"],
    },

    "b8": {
        name: "Nidadavole Venkat Ramayya",
        description: ["Tanuku, adopted from Chitturi?"],
        spouse: ["b2"],
        parents: [],
        siblings: [],
        children: ["c2","c3","c4","c5"],
        adopted: [],
        gavechild: ["c1","b1"],
    },

    "b3": {
        name: "Mullapudi Achhayama",
        description: ["Tanuku"],
        spouse: ["b9"],
        parents: ["a2","a3"],
        siblings: ["b1","b2","b4","b5","b6","b7"],
        children: ["c6","c7","c8","c9","c10"],
        adopted: [],
        gavechild: [],
    },

    "b9": {
        name: "Chitturi Inderayya",
        description: ["Tanuku"],
        spouse: ["b3"],
        parents: [],
        siblings: [],
        children: ["c6","c7","c8","c9","c10"],
        adopted: [],
        gavechild: [],
    },

    "b4": {
        name: "Mullapudi Thimmaraja",
        description: ["Tanuku"],
        spouse: ["b10","b11"],
        parents: ["a2","a3"],
        siblings: ["b1","b2","b3","b5","b6","b7"],
        children: ["c11","c12","c13","c14","c15","c16"],
        adopted: [],
        gavechild: [],
    },
    
 "b10": {
        name: "Bolla Venkatramanamma",
        description: ["first wife"],
        spouse: ["b4"],
        parents: [],
        siblings: ["b15"],
        children: ["c11","c12"],
        adopted: [],
        gavechild: [],
    },
    
    "b11": {
        name: "? Kamala",
        description: ["2nd wife"],
        spouse: ["b4"],
        parents: [],
        siblings: [],
        children: ["c13","c14","c15","c16"],
        adopted: [],
        gavechild: [],
    },

    "b5": {
        name: "Mullapudi Bullinarayanamma",
        description: ["Dommeru"],
        spouse: ["b12"],
        parents: ["a2","a3"],
        siblings: ["b1","b2","b3","b4","b6","b7"],
        children: ["c17","c18","c19","c20","c21","c22","c23","c24","c25","c26"],
        adopted: [],
        gavechild: [],
    },

    "b12": {
        name: "Yalamarthi Sattiraju",
        description: ["Dommeru"],
        spouse: ["b5"],
        parents: [],
        siblings: [],
        children: ["c17","c18","c19","c20","c21","c22","c23","c24","c25","c26"],
        adopted: [],
        gavechild: [],
    },

    "b6": {
        name: "Mullapudi Sri Lakshmi",
        description: ["Kolla"],
        spouse: ["b13"],
        parents: ["a2","a3"],
        siblings: ["b1","b2","b3","b4","b5","b7"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "b13": {
        name: "? Chitturi",
        description: ["Kolla"],
        spouse: ["b6"],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "b7": {
        name: "Mullapudi Lakshmi Devi",
        description: ["Kolla"],
        spouse: ["b14"],
        parents: ["a2","a3"],
        siblings: ["b1","b2","b3","b4","b5","b6"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "b14": {
        name: "? Chitturi",
        description: ["Kolla"],
        spouse: ["b7"],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "b15": {
        name: "Bolla Veera Venkanna",
        description: ["not sure how many kids"],
        spouse: ["b16"],
        parents: [],
        siblings: [],
        children: ["d59"],
        adopted: [],
        gavechild: [],
    },

    "b16": {
        name: "? Ramalakshmi",
        description: [],
        spouse: ["b15"],
        parents: [],
        siblings: [],
        children: ["d59"],
        adopted: [],
        gavechild: [],
    },

    "c1": {
        name: "Pendyala Sri Ramachandra Venkata Krishna Ranga Rao",
        description: [],
        spouse: ["c11"],
        parents: ["a1","b1"],
        siblings: [],
        children: ["d1","d2","d3","d4","d5","d6","d7","d8","d9","d10","d11","d12"],
        adopted: [],
        gavechild: [],
    },

    "c11": {
        name: "Mullapudi Atchamamba",
        description: [],
        spouse: ["c1"],
        parents: ["b4","b10"],
        siblings: ["c12","c13","c14","c15","c16"],
        children: ["d1","d2","d3","d4","d5","d6","d7","d8","d9","d10","d11","d12"],
        adopted: [],
        gavechild: [],
    },

    "c2": {
        name: "Nidadavole Lakshmikantamma",
        description: [],
        spouse: ["c27"],
        parents: ["b2","b8"],
        siblings: ["c3","c4","c5"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "c27": {
        name: "Dukkipati ?",
        description: [],
        spouse: ["c2"],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "c3": {
        name: "Nidadavole Chandramati",
        description: [],
        spouse: ["c12"],
        parents: ["b2","b8"],
        siblings: ["c2","c4","c5"],
        children: ["c29","d24","d25","d26","d27","d28","d29","d30"],
        adopted: [],
        gavechild: [],
    },

    "c12": {
        name: "Mullapudi Harishchandra Prasad",
        description: [],
        spouse: ["c3"],
        parents: ["b4","b10"],
        siblings: ["c11","c13","c14","c15","c16"],
        children: ["c29","d24","d25","d26","d27","d28","d29","d30"],
        adopted: [],
        gavechild: [],
    },

    "c4": {
        name: "Nidadavole Surendranath",
        description: [],
        spouse: ["c28"],
        parents: ["b2","b8"],
        siblings: ["c2","c3","c5"],
        children: ["d13","d14","d15","d16","d17"],
        adopted: [],
        gavechild: [],
    },

    "c28": {
        name: "Jagarlamudi Kanakadurga Devi",
        description: [],
        spouse: ["c4"],
        parents: [],
        siblings: ["d58"],
        children: ["d13","d14","d15","d16","d17"],
        adopted: [],
        gavechild: [],
    },

    "d58": {
        name: "Jagarlamudi Hari Babu",
        description: [],
        spouse: ["d1"],
        parents: [],
        siblings: ["c28"],
        children: ["e1","e2","e3","e4","e5"],
        adopted: [],
        gavechild: [],
    },

    "d1": {
        name: "Pendyala Akkamamba",
        description: ["Chirala Peddi"],
        spouse: ["d58"],
        parents: ["c1","c11"],
        siblings: ["e1","e2","e3","e4","e5"],
        children: ["d2","d3","d4","d5","d6","d7","d8","d9","d10","d11","d12"],
        adopted: [],
        gavechild: [],
    },

    "c5": {
        name: "Nidadavole Mruthyunjay Rao",
        description: [],
        spouse: ["c29"],
        parents: ["b2","b8"],
        siblings: ["c2","c3","c4"],
        children: ["d18","d19","d20","d21","d22"],
        adopted: [],
        gavechild: [],
    },

    "c29": {
        name: "Mullapudi Venkatramanamma",
        description: [],
        spouse: ["c5"],
        parents: ["c3","c12"],
        siblings: ["d24","d25","d26","d27","d28","d29","d30"],
        children: ["d18","d19","d20","d21","d22"],
        adopted: [],
        gavechild: [],
    },

    "c6": {
        name: "Chitturi Krishna Rao",
        description: [],
        spouse: ["c13"],
        parents: ["b3","b9"],
        siblings: ["c7","c8","c9","c10"],
        children: [],
        adopted: [], 
        gavechild: [],
    },

    "c13": {
        name: "Mullapudi Ramanamma",
        description: [],
        spouse: ["c6"],
        parents: ["b4","b11"],
        siblings: ["c11","c12","c14","c15","c16"],
        children: [],
        adopted: ["d23","d31"],
        gavechild: [],
    },

    "c7": {
        name: "Chitturi Prakash Rao",
        description: [],
        spouse: ["c30"],
        parents: ["b3","b9"],
        siblings: ["c6","c8","c9","c10"],
        children: [],
        adopted: [], 
        gavechild: [],
    },

    "c30": {
        name: "Anusuya",
        description: [],
        spouse: ["c30"],
        parents: [],
        siblings: [],
        children: [],
        adopted: [], 
        gavechild: [],
    },

    "c8": {
        name: "Chitturi Suryakantham",
        description: [],
        spouse: ["c31"],
        parents: ["b3","b9"],
        siblings: ["c6","c7","c9","c10"],
        children: [],
        adopted: [], 
        gavechild: [],
    },

    "c31": {
        name: "Alluri Bappanayudu",
        description: [],
        spouse: ["c9"],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "c9": {
        name: "Chitturi Nagaratna",
        description: [],
        spouse: ["c32"],
        parents: ["b3","b9"],
        siblings: ["c6","c7","c8","c10"],
        children: [],
        adopted: [], 
        gavechild: [],
    },

    "c32": {
        name: "Alluri Sarvarayudu",
        description: [],
        spouse: ["c9"],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "c10": {
        name: "Chitturi Chandramati",
        description: [],
        spouse: ["c33"],
        parents: ["b3","b9"],
        siblings: ["c6","c7","c8","c9"],
        children: [],
        adopted: [], 
        gavechild: [],
    },

    "33": {
        name: "?",
        description: [],
        spouse: ["c10"],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "c14": {
        name: "Mullapudi Ganga Bhavani",
        description: ["2nd wife"],
        spouse: ["c34"],
        parents: ["b4","b11"],
        siblings: ["c11","c12","c13","c15","c16"],
        children: ["d31","d32","d33"],
        adopted: [],
        gavechild: ["d34"],
    },

    "c34": {
        name: "Jagarlamudi Chandramouli",
        description: [],
        spouse: ["c35","c34"],
        parents: [],
        siblings: [],
        children: ["g1","d31","d32","d33"],
        adopted: [],
        gavechild: ["d34"],
    },

    "c35": {
        name: "? Indira",
        description: [],
        spouse: ["c34"],
        parents: [],
        siblings: [],
        children: ["g1"],
        adopted: [],
        gavechild: [],
    },

    "c15": {
        name: "Mullapudi Rajeshwari",
        description: [],
        spouse: ["c17"],
        parents: ["b4","b11"],
        siblings: ["c11","c12","c13","c14","c16"],
        children: [],
        adopted: [["d34","c14"],["d35","d3"]],
        gavechild: [],
    },

    "c16": {
        name: "Mullapudi Narendranath Chowdary",
        description: [],
        spouse: [],
        parents: ["b4","b11"],
        siblings: ["c11","c12","c13","c14","c15"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "c17": {
        name: "Yalamarthi Narayan Rao",
        description: [],
        spouse: ["c15"],
        parents: ["b5","b12"],
        siblings: ["c18","c19","c20","c21","c22","c23","c24","c25","c26"],
        children: [],
        adopted: [["d34","c14"],["d35","d3"]],
        gavechild: [],
    },

    "c18": {
        name: "Yalamarthi Saraswati",
        description: ["adopted her child"],
        spouse: ["c36"],
        parents: ["b5","b12"],
        siblings: ["c17","c19","c20","c21","c22","c23","c24","c25","c26"],
        children: [],
        adopted: ["d36"],
        gavechild: [],
    },

    "c36": {
        name: "Kondapalli Atchanna",
        description: [],
        spouse: ["c18"],
        parents: [],
        siblings: [],
        children: [],
        adopted: ["d36"],
        gavechild: [],
    },

    "c19": {
        name: "Yalamarthi Padmavati",
        description: [],
        spouse: ["c37"],
        parents: ["b5","b12"],
        siblings: ["c17","c18","c20","c21","c22","c23","c24","c25","c26"],
        children: ["d37","d38","d39","d40"],
        adopted: [],
        gavechild: [],
    },

    "c37": {
        name: "Maddipoti Subba Rao",
        description: [],
        spouse: ["c19"],
        parents: [],
        siblings: [],
        children: ["d37","d38","d39","d40"],
        adopted: [],
        gavechild: [],
    },

    "c20": {
        name: "Yalamarthi Anusuya",
        description: [],
        spouse: ["c38"],
        parents: ["b5","b12"],
        siblings: ["c17","c18","c19","c21","c22","c23","c24","c25","c26"],
        children: ["c43","d41","d42","d43"],
        adopted: [],
        gavechild: [],
    },

    "c38": {
        name: "Jujjavarapu ?",
        description: [],
        spouse: ["c20"],
        parents: [],
        siblings: [],
        children: ["c43","d41","d42","d43"],
        adopted: [],
        gavechild: [],
    },

    "c21": {
        name: "Yalamarthi Ramanamma",
        description: [],
        spouse: ["c39"],
        parents: ["b5","b12"],
        siblings: ["c17","c18","c19","c20","c22","c23","c24","c25","c26"],
        children: ["d44"],
        adopted: [],
        gavechild: [],
    },

    "c39": {
        name: "Manyam Madhav Rao",
        description: [],
        spouse: ["c21"],
        parents: [],
        siblings: [],
        children: ["d44"],
        adopted: [],
        gavechild: [],
    },

    "c22": {
        name: "Yalamarthi Bapayamma",
        description: [],
        spouse: ["c40"],
        parents: ["b5","b12"],
        siblings: ["c17","c18","c19","c20","c21","c23","c24","c25","c26"],
        children: ["d45"],
        adopted: [],
        gavechild: [],
    },

    "c40": {
        name: "Koduri Bhaskar Rao",
        description: [],
        spouse: ["c22"],
        parents: [],
        siblings: [],
        children: ["d45"],
        adopted: [],
        gavechild: [],
    },

    "c23": {
        name: "Yalamarthi Venkat Rayudu",
        description: [],
        spouse: ["c41"],
        parents: ["b5","b12"],
        siblings: ["c17","c18","c19","c20","c21","c22","c24","c25","c26"],
        children: ["d46","d47","d48"],
        adopted: [],
        gavechild: [],
    },

    "c41": {
        name: "? Ramasekharam",
        description: [],
        spouse: ["c23"],
        parents: [],
        siblings: [],
        children: ["d46","d47","d48"],
        adopted: [],
        gavechild: [],
    },

    "c24": {
        name: "Yalamarthi Venkat Rao",
        description: [],
        spouse: ["c42"],
        parents: ["b5","b12"],
        siblings: ["c17","c18","c19","c20","c21","c22","c23","c25","c26"],
        children: ["d49","d50","d51"],
        adopted: [],
        gavechild: [],
    },

    "c42": {
        name: "? Lakshmi",
        description: [],
        spouse: ["c24"],
        parents: [],
        siblings: [],
        children: ["d49","d50","d51"],
        adopted: [],
        gavechild: [],
    },

    "c25": {
        name: "Yalamarthi Atchuta Ramayya",
        description: [],
        spouse: ["c43"],
        parents: ["b5","b12"],
        siblings: ["c17","c18","c19","c20","c21","c22","c23","c24","c26"],
        children: ["d52","d53","d54"],
        adopted: [],
        gavechild: [],
    },

    "c43": {
        name: "Jujjavarapu Gayatri",
        description: [],
        spouse: ["c25"],
        parents: ["c20","c38"],
        siblings: ["d41","d42","d43"],
        children: ["d52","d53","d54"],
        adopted: [],
        gavechild: [],
    },
    
    "c26": {
        name: "Yalamarthi Akkamamba",
        description: [],
        spouse: ["c44"],
        parents: ["b5","b12"],
        siblings: ["c17","c18","c19","c20","c21","c22","c23","c24","c25"],
        children: ["d55","d56","d57"],
        adopted: [],
        gavechild: [],
    },

    "c44": {
        name: "Nutakki Gauri Shankar",
        description: [],
        spouse: ["c26"],
        parents: [],
        siblings: [],
        children: ["d55","d56","d57"],
        adopted: [],
        gavechild: [],
    },

    "d2": {
        name: "Pendyala Venkataramanamma",
        description: ["Bangla peddi"],
        spouse: ["d59"],
        parents: ["c1","c11"],
        siblings: ["d1","d3","d4","d5","d6","d7","d8","d9","d10","d11","d12"],
        children: ["e5","e6"],
        adopted: [],
        gavechild: [],
    },

    "d59": {
        name: "Bolla Satyanarayana",
        description: ["any siblings?"],
        spouse: ["d2"],
        parents: ["b15","b16"],
        siblings: [],
        children: ["e5","e6"],
        adopted: [],
        gavechild: [],
    },

    "d3": {
        name: "Pendyala Ramalakshmi",
        description: ["Coimbatore"],
        spouse: ["d60"],
        parents: ["c1","c11"],
        siblings: ["d1","d2","d4","d5","d6","d7","d8","d9","d10","d11","d12"],
        children: ["e7","e8","e9","e10"],
        adopted: [],
        gavechild: ["d35"],
    },

    "d60": {
        name: "R. Ethiraj",
        description: [],
        spouse: ["d3"],
        parents: [],
        siblings: [],
        children: ["e7","e8","e9","e10"],
        adopted: [],
        gavechild: ["d35"],
    },

    "d4": {
        name: "Pendyala Ananthalakshmi",
        description: ["Hyderabad"],
        spouse: ["d61"],
        parents: ["c1","c11"],
        siblings: ["d1","d2","d3","d5","d6","d7","d8","d9","d10","d11","d12"],
        children: ["e11","e12","e13","e14"],
        adopted: [],
        gavechild: [],
    },

    "d61": {
        name: "Nuthakki Bhanu Prasad",
        description: [""],
        spouse: ["d4"],
        parents: [],
        siblings: [],
        children: ["e11","e12","e13","e14"],
        adopted: [],
        gavechild: [],
    },

    "e11": {
        name: "Nuthakki Ram Prasad",
        description: [],
        spouse: ["e62"],
        parents: ["d4","d64"],
        siblings: ["e12","e13","e14"],
        children: ["f7","f8"],
        adopted: [],
        gavechild: [],
    },

    "e62": {
        name: "Alluri Nagaratna",
        description: [],
        spouse: ["e11"],
        parents: [],
        siblings: [],
        children: ["f7","f8"],
        adopted: [],
        gavechild: [],
    },

    "f7": {
        name: "Nuthakki Venkata Bhanu Prasad",
        description: [],
        spouse: [],
        parents: ["e11","e62"],
        siblings: ["f8"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "f8": {
        name: "Nuthakki Supriya",
        description: [],
        spouse: ["f9"],
        parents: ["e11","e62"],
        siblings: ["f7"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "f9": {
        name: "Namala Srinivas",
        description: ["Vasu"],
        spouse: ["f8"],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e12": {
        name: "Nuthakki Ranga Prasad",
        description: [],
        spouse: [],
        parents: ["d4","d64"],
        siblings: ["e11","e13","e14"],
        children: ["f10","f11"],
        adopted: [],
        gavechild: [],
    },

    "f10": {
        name: "Rahul Nuthakki Prasad",
        description: [],
        spouse: [],
        parents: ["e12"],
        siblings: ["f11"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "f11": {
        name: "Ranjit Nuthakki Prasad",
        description: [],
        spouse: ["f12"],
        parents: ["e12"],
        siblings: ["f10"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "f12": {
        name: "Devyani Reddy",
        description: [],
        spouse: ["f11"],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e13": {
        name: "Nuthakki Ravi Prasad",
        description: [],
        spouse: ["e63"],
        parents: ["d4","d64"],
        siblings: ["e11","e12","e14"],
        children: ["f13","f15"],
        adopted: [],
        gavechild: [],
    },

    "e63": {
        name: "Manne Ramaparvati",
        description: [],
        spouse: ["e13"],
        parents: [],
        siblings: [],
        children: ["f13","f15"],
        adopted: [],
        gavechild: [],
    },

    "f13": {
        name: "Nuthakki Ram Prasad",
        description: ["Sriram"],
        spouse: ["f14"],
        parents: ["e13","e63"],
        siblings: ["f15"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "f14": {
        name: "Gogineni Divya",
        description: [],
        spouse: ["f13"],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },
    
    "f15": {
        name: "Nuthakki Lakshmi",
        description: [],
        spouse: ["f16"],
        parents: ["e13","e63"],
        siblings: ["f13"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "f16": {
        name: "Thotakura Meghasgyam",
        description: [],
        spouse: ["f15"],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e14": {
        name: "Nuthakki Rajender Prasad",
        description: [],
        spouse: ["e64"],
        parents: ["d4","d64"],
        siblings: ["e11","e12","e13"],
        children: ["f17","f18"],
        adopted: [],
        gavechild: [],
    },

    "e64": {
        name: "Urmi Thakkar",
        description: [],
        spouse: ["e14"],
        parents: [],
        siblings: [],
        children: ["f17","f18"],
        adopted: [],
        gavechild: [],
    },

    "f17": {
        name: "Aditya Nuthakki Prasad",
        description: [],
        spouse: [],
        parents: ["e14","e64"],
        siblings: ["f18"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "f18": {
        name: "Nandini Nuthakki Prasad",
        description: [],
        spouse: [],
        parents: ["e14","e64"],
        siblings: ["f17"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d5": {
        name: "Pendyala Satyanarayanamma",
        description: [""],
        spouse: ["d24"],
        parents: ["c1","c11"],
        siblings: ["d1","d2","d3","d4","d6","d7","d8","d9","d10","d11","d12"],
        children: ["e28","e29","e30"],
        adopted: [],
        gavechild: [],
    },

    "d24": {
        name: "Mullapudi Venkat Rayudu",
        description: [""],
        spouse: ["d5"],
        parents: ["c12","c3"],
        siblings: ["c29","d25","d26","d27","d28","d29","d30"],
        children: ["e28","e29","e30"],
        adopted: [],
        gavechild: [],
    },

    "e28": {
        name: "MSRVK Ranga Rao",
        description: [],
        spouse: ["e73"],
        parents: ["d5","d24"],
        siblings: ["e29","e30"],
        children: ["f19","f21","f23"],
        adopted: [],
        gavechild: [],
    },

    "e73": {
        name: "? Srivani",
        description: [],
        spouse: ["e28"],
        parents: [],
        siblings: [],
        children: ["f19","f21","f23"],
        adopted: [],
        gavechild: [],
    },

    "f19": {
        name: "Venkat Rayudu Mullapudi ",
        description: [],
        spouse: ["f20"],
        parents: ["e28","e73"],
        siblings: ["f21","f23"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "f20": {
        name: "Siri Ravipati",
        description: [],
        spouse: ["f19"],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "f21": {
        name: "Rukmini Mullapudi ",
        description: [],
        spouse: ["f22"],
        parents: ["e28","e73"],
        siblings: ["f19","f23"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "f22": {
        name: "Rushyant Mulpuri",
        description: [],
        spouse: ["f21"],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "f23": {
        name: "Ramyatara Mullapudi",
        description: [],
        spouse: [],
        parents: ["e28","e73"],
        siblings: ["f19","f21"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e29": {
        name: "Mullapudi Harishchandra Prasad",
        description: ["Hari"],
        spouse: ["e74"],
        parents: ["d5","d24"],
        siblings: ["e28","e30"],
        children: ["f24"],
        adopted: [],
        gavechild: [],
    },

    "e74": {
        name: "? Renuka",
        description: [],
        spouse: ["e29"],
        parents: [],
        siblings: [],
        children: ["f24"],
        adopted: [],
        gavechild: [],
    },

    "f24": {
        name: "Shivani Mullapudi",
        description: [],
        spouse: [],
        parents: ["e29","e74"],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e30": {
        name: "Mullapudi Kamala",
        description: [],
        spouse: ["e51"],
        parents: ["d5","d24"],
        siblings: ["e28","e29"],
        children: ["f25"],
        adopted: [],
        gavechild: [],
    },

    "e51": {
        name: "Dukkipati Madhu",
        description: [],
        spouse: ["e30"],
        parents: ["d37","d81"],
        siblings: ["e52","e53"],
        children: ["f25"],
        adopted: [],
        gavechild: [],
    },

    "f25": {
        name: "Anjali Dukkipati",
        description: [],
        spouse: [],
        parents: ["e30","e51"],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d6": {
        name: "Pendyala Venkat Rayudu",
        description: [],
        spouse: ["e1"],
        parents: ["c1","c11"],
        siblings: ["d1","d2","d3","d4","d5","d7","d8","d9","d10","d11","d12"],
        children: ["e15"],
        adopted: [],
        gavechild: [],
    },

    "e1": {
        name: "Jagarlamudi Sujata",
        description: [],
        spouse: ["d6"],
        parents: ["d1","d58"],
        siblings: ["e2","e3","e4"],
        children: ["e15"],
        adopted: [],
        gavechild: [],
    },

    "e15": {
        name: "PSRVK Ranga Rao",
        description: [],
        spouse: ["e65"],
        parents: ["d6","e1"],
        siblings: [],
        children: ["f26","f27"],
        adopted: [],
        gavechild: [],
    },

    "e65": {
        name: "Chitturi Usha",
        description: [],
        spouse: ["e15"],
        parents: [],
        siblings: [],
        children: ["f26","f27"],
        adopted: [],
        gavechild: [],
    },

    "f26": {
        name: "Meghana Pendyala",
        description: [],
        spouse: [],
        parents: ["e15","e65"],
        siblings: ["f27"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "f27": {
        name: "Prithvi Pendyala",
        description: [],
        spouse: [],
        parents: ["e15","e65"],
        siblings: ["f26"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d7": {
        name: "Pendyala Narendranath Chowdary",
        description: [],
        spouse: ["e5"],
        parents: ["c1","c11"],
        siblings: ["d1","d2","d3","d4","d5","d6","d8","d9","d10","d11","d12"],
        children: ["e16"],
        adopted: [],
        gavechild: [],
    },

    "e5": {
        name: "Bolla Jhansi Jayalakshmi",
        description: [],
        spouse: ["d7"],
        parents: [],
        siblings: ["e6"],
        children: ["e16"],
        adopted: [],
        gavechild: [],
    },

    "e16": {
        name: "Pendyala Ananthalakshmi",
        description: ["Anu"],
        spouse: [],
        parents: ["e5","d7"],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d8": {
        name: "Pendyala Kamala",
        description: [],
        spouse: ["d38"],
        parents: ["c1","c11"],
        siblings: ["d1","d2","d3","d4","d5","d6","d7","d9","d10","d11","d12"],
        children: ["e54","e55",'e56'],
        adopted: [],
        gavechild: [],
    },

    "d38": {
        name: "Maddipoti Jogendarnath Chowdary",
        description: [],
        spouse: ["d8"],
        parents: ["c19","c37"],
        siblings: ["d37","d39","d40"],
        children: ["e54","e55",'e56'],
        adopted: [],
        gavechild: [],
    },

    "e54": {
        name: "Maddipoti Venkat Rayudu",
        description: [],
        spouse: [],
        parents: ["d8","d38"],
        siblings: ["e55",'e56'],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e55": {
        name: "Maddipoti Padma",
        description: [],
        spouse: [],
        parents: ["d8","d38"],
        siblings: ["e54",'e56'],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e56": {
        name: "Maddipoti Subba Rao",
        description: [],
        spouse: [],
        parents: ["d8","d38"],
        siblings: ["e54",'e55'],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d9": {
        name: "Pendyala Venkat Krishna Rao",
        description: [],
        spouse: ["d62"],
        parents: ["c1","c11"],
        siblings: ["d1","d2","d3","d4","d5","d6","d7","d8","d10","d11","d12"],
        children: ["e17","e18","e19"],
        adopted: [],
        gavechild: [],
    },

    "d62": {
        name: "Manne Nagamani Devi",
        description: [],
        spouse: ["d9"],
        parents: [],
        siblings: ["e60"],
        children: ["e17","e18","e19"],
        adopted: [],
        gavechild: [],
    },

    "e17": {
        name: "Pendyala Rayudu",
        description: [],
        spouse: ["e66"],
        parents: ["d9","d62"],
        siblings: ["e18","e19"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e66": {
        name: "? Surekha",
        description: [],
        spouse: ["e17"],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e18": {
        name: "Pendyala Ravi",
        description: [],
        spouse: ["e67"],
        parents: ["d9","d62"],
        siblings: ["e17","e19"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e67": {
        name: "?",
        description: [],
        spouse: ["e18"],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e19": {
        name: "Pendyala Archana",
        description: [],
        spouse: ["e68"],
        parents: ["d9","d62"],
        siblings: ["e17","e18"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e68": {
        name: "Sennar Rajiv Krishna",
        description: [],
        spouse: ["e19"],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d10": {
        name: "Pendyala Achuta Ramayya",
        description: [],
        spouse: ["d63"],
        parents: ["c1","c11"],
        siblings: ["d1","d2","d3","d4","d5","d6","d7","d8","d9","d11","d12"],
        children: ["e20","e21"],
        adopted: [],
        gavechild: [],
    },

    "d63": {
        name: "? Shailaja",
        description: [],
        spouse: ["d10"],
        parents: [],
        siblings: [],
        children: ["e20","e21"],
        adopted: [],
        gavechild: [],
    },

    "e20": {
        name: "Pendyala Divya",
        description: [],
        spouse: ["e69"],
        parents: ["d10","d63"],
        siblings: ["e21"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e69": {
        name: "?",
        description: [],
        spouse: ["e20"],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e21": {
        name: "Pendyala Shruti",
        description: [],
        spouse: ["e21"],
        parents: ["d10","d63"],
        siblings: ["e20"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e70": {
        name: "?",
        description: [],
        spouse: ["e21"],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d11": {
        name: "Pendyala Ranganayiki",
        description: [],
        spouse: ["d64"],
        parents: ["c1","c11"],
        siblings: ["d1","d2","d3","d4","d5","d6","d7","d8","d9","d10","d12"],
        children: ["e22","e23"],
        adopted: [],
        gavechild: [],
    },

    "d64": {
        name: "? Krishna Mohan",
        description: [],
        spouse: ["d11"],
        parents: [],
        siblings: [],
        children: ["e22","e23"],
        adopted: [],
        gavechild: [],
    },

    "e22": {
        name: "? Sanjay",
        description: [],
        spouse: ["e71"],
        parents: ["d11","d64"],
        siblings: ["e23"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e71": {
        name: "?",
        description: [],
        spouse: ["e22"],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e23": {
        name: "? Ajay",
        description: [],
        spouse: ["e72"],
        parents: ["d11","d64"],
        siblings: ["e22"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e72": {
        name: "?",
        description: [],
        spouse: ["e23"],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d12": {
        name: "Pendyala Usha",
        description: [],
        spouse: ["d42"],
        parents: ["c1","c11"],
        siblings: ["d1","d2","d3","d4","d5","d6","d7","d8","d9","d10","d11"],
        children: ["e57","e58"],
        adopted: [],
        gavechild: [],
    },

    "d42": {
        name: "Jujjavarapu Venkat Rayudu",
        description: [],
        spouse: ["d12"],
        parents: ["c20","c38"],
        siblings: ["c43","d41","d43"],
        children: ["e57","e58"],
        adopted: [],
        gavechild: [],
    },

    "e57": {
        name: "Jujjavarapu Nagini",
        description: [],
        spouse: [],
        parents: ["d12","d42"],
        siblings: ["e58"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e58": {
        name: "Jujjavarapu Sindhu",
        description: [],
        spouse: [],
        parents: ["d12","d42"],
        siblings: ["e57"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d13": {
        name: "Nidadavole Nirmala",
        description: [],
        spouse: [],
        parents: ["c4","c28"],
        siblings: ["d14","d15","d16","d17"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d65": {
        name: "?",
        description: [],
        spouse: ["d13"],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d14": {
        name: "Nidadavole Sarla",
        description: [],
        spouse: ["d66"],
        parents: ["c4","c28"],
        siblings: ["d13","d15","d16","d17"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d66": {
        name: "?",
        description: [],
        spouse: ["d14"],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d15": {
        name: "Nidadavole Murli",
        description: [],
        spouse: ["d67"],
        parents: ["c4","c28"],
        siblings: ["d13","d14","d16","d17"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d67": {
        name: "?",
        description: [],
        spouse: ["d15"],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d16": {
        name: "Nidadavole Ram Mohan",
        description: [],
        spouse: ["d68"],
        parents: ["c4","c28"],
        siblings: ["d13","d14","d15","d17"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d68": {
        name: "?",
        description: [],
        spouse: ["d16"],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d17": {
        name: "Nidadavole Saroja",
        description: [],
        spouse: ["e2"],
        parents: ["c4","c28"],
        siblings: ["d13","d14","d15","d16"],
        children: ["f1","f2"],
        adopted: [],
        gavechild: [],
    },

    "e2": {
        name: "Jagarlamudi Suresh",
        description: [],
        spouse: ["d17"],
        parents: ["d1","d58"],
        siblings: ["e1","e3","e4"],
        children: ["f1","f2"],
        adopted: [],
        gavechild: [],
    },

    "f1": {
        name: "Jagarlamudi Kiran",
        description: [],
        spouse: [],
        parents: ["e2","d17"],
        siblings: ["f2"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "f2": {
        name: "Jagarlamudi Neelima",
        description: [],
        spouse: ["f3"],
        parents: ["e2","d17"],
        siblings: ["f1"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "f3": {
        name: "Manyam Praveen",
        description: [],
        spouse: ["f2"],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d18": {
        name: "Nidadavole Renuka",
        description: [],
        spouse: ["d29"],
        parents: ["c5","c29"],
        siblings: ["d19","d20","d21","d22"],
        children: ["e41","e42"],
        adopted: [],
        gavechild: [],
    },

    "d29": {
        name: "Mullapudi Thimmaraja",
        description: [],
        spouse: ["d18"],
        parents: ["c12","c3"],
        siblings: ["c29","d24","d25","d26","d27","d28","d30"],
        children: ["e41","e42"],
        adopted: [],
        gavechild: [],
    },

    "e41": {
        name: "Mullapudi Devi",
        description: [],
        spouse: [],
        parents: ["d29","d18"],
        siblings: ["e42"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e42": {
        name: "Mullapudi Mruthyunjay",
        description: [],
        spouse: [],
        parents: ["d29","d18"],
        siblings: ["e41"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d19": {
        name: "Nidadavole Narayanamma",
        description: [],
        spouse: ["d28"],
        parents: ["c5","c29"],
        siblings: ["d18","d20","d21","d22"],
        children: ["e38","e39","e40"],
        adopted: [],
        gavechild: [],
    },

    "d28": {
        name: "Mullapudi Narendranath",
        description: [],
        spouse: ["d19"],
        parents: ["c12","c3"],
        siblings: ["c29","d24","d25","d26","d27","d29","d30"],
        children: ["e38","e39","e40"],
        adopted: [],
        gavechild: [],
    },

    "e38": {
        name: "Mullapudi Anuradha",
        description: [],
        spouse: [],
        parents: ["d28","d19"],
        siblings: ["e39","e40"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e39": {
        name: "Mullapudi Vikram",
        description: [],
        spouse: [],
        parents: ["d28","d19"],
        siblings: ["e38","e40"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e40": {
        name: "Mullapudi Jayshree",
        description: [],
        spouse: [],
        parents: ["d28","d19"],
        siblings: ["e38","e39"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d20": {
        name: "Nidadavole Vijayvalli",
        description: [],
        spouse: ["d69"],
        parents: ["c5","c29"],
        siblings: ["d18","d19","d21","d22"],
        children: ["e24","e25"],
        adopted: [],
        gavechild: [],
    },

    "d69": {
        name: "Manyam Satyanarayana",
        description: ["kolla?"],
        spouse: ["d20"],
        parents: [],
        siblings: [],
        children: ["e24","e25"],
        adopted: [],
        gavechild: [],
    },

    "e24": {
        name: "Manyam Mruthyunjay",
        description: [],
        spouse: [],
        parents: ["d20","d69"],
        siblings: ["e25"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e25": {
        name: "Manyam Keshav",
        description: [],
        spouse: [],
        parents: ["d20","d69"],
        siblings: ["e24"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d21": {
        name: "Nidadavole Chandramati",
        description: [],
        spouse: ["d70"],
        parents: ["c5","c29"],
        siblings: ["d18","d19","d20","d22"],
        children: [],
        adopted: [],
        gavechild: [],
    },
    
    "d70": {
        name: "Jujjavarapu Phanendra",
        description: [],
        spouse: ["d21"],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d22": {
        name: "Nidadavole Ranga Rao",
        description: [],
        spouse: ["d71"],
        parents: ["c5","c29"],
        siblings: ["d18","d19","d20","d21"],
        children: ["e26","e27"],
        adopted: [],
        gavechild: [],
    },

    "d71": {
        name: "? Aparanji",
        description: ["kolla?"],
        spouse: ["d22"],
        parents: [],
        siblings: [],
        children: ["e26","e27"],
        adopted: [],
        gavechild: [],
    },

    "e26": {
        name: "Nidadavole Apoorva",
        description: [],
        spouse: [],
        parents: ["d22","d71"],
        siblings: ["e27"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e27": {
        name: "Nidadavole Apurupa",
        description: [],
        spouse: [],
        parents: ["d22","d71"],
        siblings: ["e26"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d23": {
        name: "Chitturi Kannaiya",
        description: [],
        spouse: [],
        parents: ["c6","c13"],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d25": {
        name: "Mullapudi Akkamamba",
        description: [],
        spouse: ["d73"],
        parents: ["c12","c3"],
        siblings: ["c29","d24","d26","d27","d28","d29","d30"],
        children: ["e31","e32"],
        adopted: [],
        gavechild: [],
    },

    "d73": {
        name: "? Rajunayudu",
        description: [],
        spouse: ["d25"],
        parents: [],
        siblings: [],
        children: ["e31","e32"],
        adopted: [],
        gavechild: [],
    },

    "e31": {
        name: "? Raghu",
        description: [],
        spouse: [],
        parents: ["d25","d73"],
        siblings: ["e32"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e32": {
        name: "? Ramesh",
        description: [],
        spouse: [],
        parents: ["d25","d73"],
        siblings: ["e31"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d26": {
        name: "Mullapudi Ananthalakshmi",
        description: ["Coimbatore"],
        spouse: ["d74"],
        parents: ["c12","c3"],
        siblings: ["c29","d24","d25","d26","d27","d28","d29","d30"],
        children: ["e33","e34","e35"],
        adopted: [],
        gavechild: [],
    },

    "d74": {
        name: "? Jayaram",
        description: [],
        spouse: ["d26"],
        parents: [],
        siblings: [],
        children: ["e33","e34","e35"],
        adopted: [],
        gavechild: [],
    },

    "e33": {
        name: "? Narayan Kumar",
        description: [],
        spouse: [],
        parents: ["d26","d74"],
        siblings: ["e34","e35"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e34": {
        name: "? Harishchandra",
        description: [],
        spouse: [],
        parents: ["d26","d74"],
        siblings: ["e33","e35"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e35": {
        name: "? Ravi",
        description: [],
        spouse: [],
        parents: ["d26","d74"],
        siblings: ["e33","e34"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d27": {
        name: "Mullapudi Ramalakshmi",
        description: [],
        spouse: ["d75"],
        parents: ["c12","c3"],
        siblings: ["c29","d24","d25","d26","d27","d28","d29","d30"],
        children: ["e36","e37"],
        adopted: [],
        gavechild: [],
    },

    "d75": {
        name: "Kosaraju Surendra",
        description: [],
        spouse: ["d27"],
        parents: [],
        siblings: [],
        children: ["e36","e37"],
        adopted: [],
        gavechild: [],
    },

    "e36": {
        name: "Kosaraju Sudhakar",
        description: [],
        spouse: [],
        parents: ["d27","d75"],
        siblings: ["e37"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e37": {
        name: "Kosaraju ?",
        description: [],
        spouse: [],
        parents: ["d27","d75"],
        siblings: ["e36"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d30": {
        name: "Mullapudi Narayanamma",
        description: [],
        spouse: ["d34"],
        parents: ["c12","c3"],
        siblings: ["c29","d24","d25","d26","d27","d28","d29"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d34": {
        name: "Yalamarthi Thimmaraju",
        description: [],
        spouse: ["d30"],
        parents: ["c17","c15"],
        siblings: ["d35"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d31": {
        name: "Jagarlamudi Indira",
        description: [],
        spouse: ["d76"],
        parents: ["c14","c34"],
        siblings: ["d32","d33"],
        children: ["e43","e44"],
        adopted: [],
        gavechild: ["d23"],
    },

    "d76": {
        name: "Ramana Rao",
        description: ["?"],
        spouse: ["d31"],
        parents: [],
        siblings: [],
        children: ["e43","e44"],
        adopted: [],
        gavechild: ["d23"],
    },

    "e43": {
        name: "? Kuppuswamy",
        description: [],
        spouse: [],
        parents: ["d31","d76"],
        siblings: ["e44"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e44": {
        name: "? Kamala",
        description: [],
        spouse: [],
        parents: ["d31","d76"],
        siblings: ["e43"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d32": {
        name: "Jagarlamudi Narendranath",
        description: [],
        spouse: ["d39"],
        parents: ["c14","c34"],
        siblings: ["d31","d33"],
        children: ["e45","e46"],
        adopted: [],
        gavechild: [],
    },

    "d39": {
        name: "Maddipoti Lakshmi",
        description: [],
        spouse: ["d32"],
        parents: ["c19","c37"],
        siblings: ["d37","d38","d40"],
        children: ["e45","e46"],
        adopted: [],
        gavechild: [],
    },

    "e45": {
        name: "Jagarlamudi Kuppuswamy Chowdary",
        description: [],
        spouse: [],
        parents: ["d32","d39"],
        siblings: ["e46"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e46": {
        name: "Jagarlamudi Praveen",
        description: [],
        spouse: [],
        parents: ["d32","d39"],
        siblings: ["e45"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d33": {
        name: "Jagaralamudi Murli Mohan",
        description: [],
        spouse: ["d77"],
        parents: ["c14","c34"],
        siblings: ["d31","d32"],
        children: ["e47"],
        adopted: [],
        gavechild: [],
    },

    "d77": {
        name: "? Sunita",
        description: [],
        spouse: ["d33"],
        parents: [],
        siblings: [],
        children: ["e47"],
        adopted: [],
        gavechild: [],
    },

    "e47": {
        name: "Jagarlamudi Nami",
        description: [],
        spouse: [],
        parents: ["d33","d77"],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d35": {
        name: "Yalamarthi Lakshmi",
        description: ["Bujjamma"],
        spouse: ["d79"],
        parents: ["c15","c17"],
        siblings: ["d34"],
        children: ["e48","e49","e50"],
        adopted: [],
        gavechild: [],
    },

    "d79": {
        name: "Daggubati Suresh",
        description: [],
        spouse: ["d35"],
        parents: [],
        siblings: [],
        children: ["e48","e49","e50"],
        adopted: [],
        gavechild: [],
    },

    "e48": {
        name: "Daggubati Rana",
        description: [],
        spouse: [],
        parents: ["d35","d79"],
        siblings: ["e49","e50"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e49": {
        name: "Daggubati Malavika",
        description: [],
        spouse: [],
        parents: ["d35","d79"],
        siblings: ["e48","e50"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e50": {
        name: "Daggubati Abhiram",
        description: [],
        spouse: [],
        parents: ["d35","d79"],
        siblings: ["e48","e49"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d36": {
        name: "Kondapally Venkatesh",
        description: [],
        spouse: [],
        parents: ["c18","c36"],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d37": {
        name: "Maddipoti Vijendra",
        description: [],
        spouse: ["d81"],
        parents: ["c19","c37"],
        siblings: ["d38","d39","d40"],
        children: ["e51","e52","e53"],
        adopted: [],
        gavechild: [],
    },

    "d81": {
        name: "Dukkipati Sitaram Swamy",
        description: [],
        spouse: ["d37"],
        parents: [],
        siblings: [],
        children: ["e51","e52","e53"],
        adopted: [],
        gavechild: [],
    },

    "e52": {
        name: "Dukkipati Subba Rao",
        description: [],
        spouse: [],
        parents: ["d37","d81"],
        siblings: ["e51","e53"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e53": {
        name: "Dukkipati Srinivas",
        description: [],
        spouse: [],
        parents: ["d37","d81"],
        siblings: ["e51","e52"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d40": {
        name: "Maddipoti Raja",
        description: [],
        spouse: [],
        parents: ["c19","c37"],
        siblings: ["d37","d38","d39"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d41": {
        name: "Jujjavarapu Lakshmi",
        description: [],
        spouse: ["d82"],
        parents: ["c20","c38"],
        siblings: ["c43","d42","d43"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d82": {
        name: "Chitturi Gokhale",
        description: [],
        spouse: ["d41"],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },
  
    "d43": {
        name: "Jujjavarapu Kumari",
        description: [],
        spouse: [],
        parents: ["c20","c38"],
        siblings: ["c43","d41","d42"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d44": {
        name: "Manyam Shyam",
        description: [],
        spouse: [],
        parents: ["c21","c39"],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d45": {
        name: "Koduri Satish",
        description: [],
        spouse: [],
        parents: ["c22","c40"],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d46": {
        name: "Yalamarthi Ram",
        description: [],
        spouse: [],
        parents: ["c23","c41"],
        siblings: ["d47","d48"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d47": {
        name: "Yalamarthi Satyanagender Rao",
        description: [],
        spouse: [],
        parents: ["c23","c41"],
        siblings: ["d46","d48"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d48": {
        name: "Yalamarthi Ranganayiki",
        description: [],
        spouse: [],
        parents: ["c23","c41"],
        siblings: ["d46","d47"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d49": {
        name: "Yalamarthi Prasad?",
        description: [],
        spouse: [],
        parents: ["c24","c42"],
        siblings: ["d50","d51"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d50": {
        name: "Yalamarthi ?",
        description: [],
        spouse: [],
        parents: ["c24","c42"],
        siblings: ["d49","d51"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d51": {
        name: "Yalamarthi Krishna Rao",
        description: [],
        spouse: [],
        parents: ["c24","c42"],
        siblings: ["d49","d50"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d52": {
        name: "Yalamarthi Srinivas",
        description: [],
        spouse: [],
        parents: ["c25","c43"],
        siblings: ["d53","d54"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d53": {
        name: "Yalamarthi Satish",
        description: [],
        spouse: [],
        parents: ["c25","c43"],
        siblings: ["d52","d54"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d54": {
        name: "Yalamarthi Sujini",
        description: [],
        spouse: [],
        parents: ["c25","c43"],
        siblings: ["d52","d53"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d55": {
        name: "Nutakki Srinivas",
        description: [],
        spouse: ["d78"],
        parents: ["c26","c44"],
        siblings: ["d56","d57"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d78": {
        name: "Mona Patel",
        description: [],
        spouse: ["d55"],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d56": {
        name: "",
        description: [],
        spouse: [],
        parents: ["c26","c44"],
        siblings: ["d55","d57"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "d57": {
        name: "",
        description: [],
        spouse: [],
        parents: ["c26","c44"],
        siblings: ["d55","d56"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e3": {
        name: "Jagarlamudi Tulasi",
        description: [],
        spouse: ["e59"],
        parents: ["d1","d58"],
        siblings: ["e1","e2","e4"],
        children: ["f4","f5"],
        adopted: [],
        gavechild: [],
    },

    "e59": {
        name: "P. Rajkumar",
        description: [],
        spouse: ["e3"],
        parents: [],
        siblings: [],
        children: ["f4","f5"],
        adopted: [],
        gavechild: [],
    },

    "f4": {
        name: "?",
        description: [],
        spouse: [],
        parents: ["e3","e59"],
        siblings: ["f5"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "f5": {
        name: "?",
        description: [],
        spouse: [],
        parents: ["e3","e59"],
        siblings: ["f4"],
        children: [],
        adopted: [],
        gavechild: [],
    },
    "e4": {
        name: "Jagarlamudi Asha",
        description: [],
        spouse: ["e60"],
        parents: ["d1","d58"],
        siblings: ["e1","e2","e3"],
        children: ["f6"],
        adopted: [],
        gavechild: [],
    },

    "e60": {
        name: "Manne Satyanarayan",
        description: [],
        spouse: ["e4"],
        parents: [],
        siblings: ["e62"],
        children: ["f6"],
        adopted: [],
        gavechild: [],
    },

    "f6": {
        name: "Manne Nagender",
        description: [],
        spouse: [],
        parents: ["e4","e60"],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e6": {
        name: "Bolla Ramesh",
        description: [],
        spouse: ["e61"],
        parents: ["d2","d59"],
        siblings: ["e5"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e61": {
        name: "Alluri Rama",
        description: [],
        spouse: ["e6"],
        parents: [],
        siblings: [],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e7": {
        name: "Swarna Ethiraj",
        description: [],
        spouse: [],
        parents: ["d3","d60"],
        siblings: ["e8","e9","e10"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e8": {
        name: "Satyanarayana Ethiraj",
        description: [],
        spouse: [],
        parents: ["d3","d60"],
        siblings: ["e7","e9","e10"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e9": {
        name: "Ranga Rao Ethiraj",
        description: ["Bulli"],
        spouse: [],
        parents: ["d3","d60"],
        siblings: ["e7","e8","e10"],
        children: [],
        adopted: [],
        gavechild: [],
    },

    "e10": {
        name: "Silesh Ethiraj",
        description: [],
        spouse: [],
        parents: ["d3","d60"],
        siblings: ["e7","e8","e9"],
        children: [],
        adopted: [],
        gavechild: [],
    }

}


export default family;